function [Y,Xf,Af] = myAnn_ace_all(X,~,~)
%MYANN4SONEIDENSIS_ACE_ALL neural network simulation function.
%
% Auto-generated by MATLAB, 09-May-2022 22:20:44.
% 
% [Y] = myAnn4Soneidensis_ace_all(X,~,~) takes these arguments:
% 
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = 2xQ matrix, input #1 at timestep ts.
% 
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = 2xQ matrix, output #1 at timestep ts.
% 
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [0.00183745389773955;0.000316206541793929];
x1_step1.gain = [0.45588869858934;0.455627011339342];
x1_step1.ymin = -1;

% Layer 1
b1 = [0.28901162234253036099;0.46961452766811156989;-0.20958529421237850898;-0.61251623918290798443;0.16198095193677436443;3.6219993159538876881];
IW1_1 = [2.0850513722933339267 -1.6676270588603245848;-0.44852846652845573816 1.0294214254748712545;-0.071517825966309719887 0.0059486349840339172376;0.28233361685088220749 -0.29128669363844228446;1.051697614973018835 -0.91568071135772555191;14.28305001588014278 -11.615529411803192872];

% Layer 2
b2 = [1.2577033338215080072;-0.81426945752878887586;-1.5128792153066981108;0.013065635238935604731;-1.0716935274407675127;-3.6959983380805798703];
LW2_1 = [0.018719671596271077879 0.10824272135413989804 3.2755739009692033115 0.23745461009176191403 -0.0055631361850416918141 -0.00039902855013321789947;0.077364132773007243671 0.046179896144692034188 -1.8613032984069219911 -0.96477111427126516219 -0.14790810614235663789 -0.00029000357484211167734;3.1492696972766620611 0.027009506742497923354 0.10045487955749671238 1.6414351052038149703 0.44822947568607146573 3.2716058774292124944;0.32451776480302740868 -3.2825080893326639142 1.7840976811962510062 1.275024474068436886 -0.91365762295161756512 -0.36760026410660118223;-0.009741442140799879898 0.0016832317335775995835 1.9234882566447593089 -0.65963792736020909757 -0.34486847758661531849 -0.0029459956456575463885;-0.72076345252283713361 -0.006674645261298850496 0.41412319658646157272 -0.098467626947882067046 -0.73462942213257265145 4.2651141005448822696];

% Layer 3
b3 = [1.8403529856244538188;0.020449675933352735868];
LW3_2 = [3.1222448094605295132 -3.9304074910865636205 0.31271004157329679307 -0.0020170449983926020537 3.7226242333069041734 -0.34874516195655619333;-4.827040488821964459 2.438968437517256671 -0.14286320822434794842 -0.32600971927881505774 -2.093435929111407745 0.15642105988402496553];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = [0.455627011339342;30.0703332620161];
y1_step1.xoffset = [-4.38987158896059;3.12893062561455e-05];

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
  X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
  Q = size(X{1},2); % samples/series
else
  Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS

    % Input 1
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = tansig_apply(repmat(b2,1,Q) + LW2_1*a1);
    
    % Layer 3
    a3 = repmat(b3,1,Q) + LW3_2*a2;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a3,y1_step1);
end

% Final Delay States
Xf = cell(1,0);
Af = cell(3,0);

% Format Output Arguments
if ~isCellX
  Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
  y = bsxfun(@minus,x,settings.xoffset);
  y = bsxfun(@times,y,settings.gain);
  y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
  a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
  x = bsxfun(@minus,y,settings.ymin);
  x = bsxfun(@rdivide,x,settings.gain);
  x = bsxfun(@plus,x,settings.xoffset);
end
